packages:
  - "apps/*"
  - "packages/**"
  - "tooling/*"
  - "admin"

# Define a catalog of version ranges.
catalog:
  zod: ^3.24.2
  react: ^19.1.2
  "@types/react": ^19.1.2
  "react-dom": ^19.1.2
  "@types/react-dom": ^19.1.2
  "@types/node": ^24.7.1
  typescript: ^5.9.3
