packages:
  - "apps/*"
  - "packages/**"
  - "tooling/*"
  - "admin"

# Define a catalog of version ranges.
catalog:
  zod: ^3.24.2
  react: ">=19.1.2 <19.2.0 || >=19.2.1"
  "@types/react": ^19.0.0
  "react-dom": ">=19.1.2 <19.2.0 || >=19.2.1"
  "@types/react-dom": ^19.0.0
  "@types/node": ^24.7.1
  typescript: ^5.9.3
