packages:
  - "apps/*"
  - "packages/**"
  - "tooling/*"

# Define a catalog of version ranges.
catalog:
  zod: ^3.24.2
  react: ^19.0.0
  "@types/react": ^19.0.0
  "react-dom": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@types/node": ^24.7.1
  typescript: ^5.9.3
