// prettier-ignore
const data = {
  'chromium os': 'https://upload.wikimedia.org/wikipedia/commons/2/28/Chromium_Logo.svg',
  'mac os': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/MacOS_logo.svg/1200px-MacOS_logo.svg.png',
  'mobile safari': 'https://upload.wikimedia.org/wikipedia/commons/5/52/Safari_browser_logo.svg',
  'openpanel.dev': 'https://openpanel.dev',
  'samsung internet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Samsung_Internet_logo.svg/1024px-Samsung_Internet_logo.svg.png',
  'vstat.info': 'https://vstat.info',
  'yahoo!': 'https://yahoo.com',
  android: 'https://image.similarpng.com/very-thumbnail/2020/08/Android-icon-on-transparent--background-PNG.png',
  bing: 'https://bing.com',
  chrome: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Google_Chrome_icon_%28February_2022%29.svg',
  chromecast: 'https://upload.wikimedia.org/wikipedia/commons/archive/2/26/20161130022732%21Chromecast_cast_button_icon.svg',
  duckduckgo: 'https://duckduckgo.com',
  ecosia: 'https://ecosia.com',
  edge: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Microsoft_Edge_logo_%282019%29.png',
  facebook: 'https://facebook.com',
  firefox: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Firefox_logo%2C_2019.svg/1920px-Firefox_logo%2C_2019.svg.png',
  github: 'https://github.com',
  gmail: 'https://mail.google.com',
  google: 'https://google.com',
  instagram: 'https://instagram.com',
  ios: 'https://cdn0.iconfinder.com/data/icons/flat-round-system/512/apple-1024.png',
  linkedin: 'https://linkedin.com',
  linux: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg',
  microlaunch: 'https://microlaunch.net',
  openalternative: 'https://openalternative.co',
  opera: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Opera_2015_icon.svg/1920px-Opera_2015_icon.svg.png',
  pinterest: 'https://www.pinterest.se',
  producthunt: 'https://www.producthunt.com',
  reddit: 'https://reddit.com',
  safari: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Safari_browser_logo.svg',
  slack: 'https://slack.com',
  snapchat: 'https://snapchat.com',
  taaft: 'https://theresanaiforthat.com',
  twitter: 'https://twitter.com',
  windows: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Windows_logo_-_2012.png',
  yandex: 'https://yandex.com',
  youtube: 'https://youtube.com',
};

export default data;
