import Head from "next/head";
import { UserDropdown } from "../UserDropdown";
import { Navbar } from "../Navbar";

type MainLayoutProps = {
  children: React.ReactNode;
  className?: string;
}

export function MainLayout({ children, className }: MainLayoutProps) {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex h-20 items-center justify-between border-b border-border bg-gradient-to-r from-blue-900 to-purple-600 px-8 text-white">
        <div className="flex flex-col [&_*]:leading-tight">
          <span className="text-2xl font-extrabold">MIXAN</span>
          <span className="text-xs text-gray-500">v0.0.1</span>
        </div>

        <Navbar />

        <div>
          <UserDropdown />
        </div>
      </nav>
      <main className={className}>
        {children}
      </main>
    </>
  );
}
