/**
 * Map a country *name* (as exported by Amplitude / MaxMind) to its ISO 3166-1
 * alpha-2 code. OpenPanel's ClickHouse `country` column is FixedString(2), so
 * anything that isn't a clean 2-letter code must be converted or dropped —
 * inserting a full name like "Nigeria" throws "Too large value for
 * FixedString(2)".
 *
 * Names are matched case-insensitively and include the common aliases MaxMind
 * uses (e.g. "Russia", "South Korea", "Czechia"). Unknown names return '' so a
 * bad/rare value never breaks the import.
 */

// Canonical ISO 3166-1 alpha-2 → English name, plus alias names that mapping
// providers commonly emit. Keys are lowercased at build time.
const NAME_TO_ALPHA2: Record<string, string> = {};

const CANONICAL: [string, string[]][] = [
  ['AD', ['Andorra']],
  ['AE', ['United Arab Emirates']],
  ['AF', ['Afghanistan']],
  ['AG', ['Antigua and Barbuda']],
  ['AI', ['Anguilla']],
  ['AL', ['Albania']],
  ['AM', ['Armenia']],
  ['AO', ['Angola']],
  ['AQ', ['Antarctica']],
  ['AR', ['Argentina']],
  ['AS', ['American Samoa']],
  ['AT', ['Austria']],
  ['AU', ['Australia']],
  ['AW', ['Aruba']],
  ['AX', ['Åland Islands', 'Aland Islands']],
  ['AZ', ['Azerbaijan']],
  ['BA', ['Bosnia and Herzegovina']],
  ['BB', ['Barbados']],
  ['BD', ['Bangladesh']],
  ['BE', ['Belgium']],
  ['BF', ['Burkina Faso']],
  ['BG', ['Bulgaria']],
  ['BH', ['Bahrain']],
  ['BI', ['Burundi']],
  ['BJ', ['Benin']],
  ['BL', ['Saint Barthélemy', 'Saint Barthelemy']],
  ['BM', ['Bermuda']],
  ['BN', ['Brunei', 'Brunei Darussalam']],
  ['BO', ['Bolivia']],
  ['BQ', ['Bonaire, Sint Eustatius and Saba', 'Caribbean Netherlands']],
  ['BR', ['Brazil']],
  ['BS', ['Bahamas', 'The Bahamas']],
  ['BT', ['Bhutan']],
  ['BV', ['Bouvet Island']],
  ['BW', ['Botswana']],
  ['BY', ['Belarus']],
  ['BZ', ['Belize']],
  ['CA', ['Canada']],
  ['CC', ['Cocos (Keeling) Islands']],
  [
    'CD',
    [
      'Congo, The Democratic Republic of the',
      'Democratic Republic of the Congo',
      'DR Congo',
    ],
  ],
  ['CF', ['Central African Republic']],
  ['CG', ['Congo', 'Republic of the Congo']],
  ['CH', ['Switzerland']],
  ['CI', ["Côte d'Ivoire", "Cote d'Ivoire", 'Ivory Coast']],
  ['CK', ['Cook Islands']],
  ['CL', ['Chile']],
  ['CM', ['Cameroon']],
  ['CN', ['China']],
  ['CO', ['Colombia']],
  ['CR', ['Costa Rica']],
  ['CU', ['Cuba']],
  ['CV', ['Cape Verde', 'Cabo Verde']],
  ['CW', ['Curaçao', 'Curacao']],
  ['CX', ['Christmas Island']],
  ['CY', ['Cyprus']],
  ['CZ', ['Czechia', 'Czech Republic']],
  ['DE', ['Germany']],
  ['DJ', ['Djibouti']],
  ['DK', ['Denmark']],
  ['DM', ['Dominica']],
  ['DO', ['Dominican Republic']],
  ['DZ', ['Algeria']],
  ['EC', ['Ecuador']],
  ['EE', ['Estonia']],
  ['EG', ['Egypt']],
  ['EH', ['Western Sahara']],
  ['ER', ['Eritrea']],
  ['ES', ['Spain']],
  ['ET', ['Ethiopia']],
  ['FI', ['Finland']],
  ['FJ', ['Fiji']],
  ['FK', ['Falkland Islands', 'Falkland Islands (Malvinas)']],
  ['FM', ['Micronesia', 'Micronesia, Federated States of']],
  ['FO', ['Faroe Islands']],
  ['FR', ['France']],
  ['GA', ['Gabon']],
  ['GB', ['United Kingdom', 'UK', 'Great Britain']],
  ['GD', ['Grenada']],
  ['GE', ['Georgia']],
  ['GF', ['French Guiana']],
  ['GG', ['Guernsey']],
  ['GH', ['Ghana']],
  ['GI', ['Gibraltar']],
  ['GL', ['Greenland']],
  ['GM', ['Gambia', 'The Gambia']],
  ['GN', ['Guinea']],
  ['GP', ['Guadeloupe']],
  ['GQ', ['Equatorial Guinea']],
  ['GR', ['Greece']],
  ['GS', ['South Georgia and the South Sandwich Islands']],
  ['GT', ['Guatemala']],
  ['GU', ['Guam']],
  ['GW', ['Guinea-Bissau']],
  ['GY', ['Guyana']],
  ['HK', ['Hong Kong']],
  ['HM', ['Heard Island and McDonald Islands']],
  ['HN', ['Honduras']],
  ['HR', ['Croatia']],
  ['HT', ['Haiti']],
  ['HU', ['Hungary']],
  ['ID', ['Indonesia']],
  ['IE', ['Ireland']],
  ['IL', ['Israel']],
  ['IM', ['Isle of Man']],
  ['IN', ['India']],
  ['IO', ['British Indian Ocean Territory']],
  ['IQ', ['Iraq']],
  ['IR', ['Iran', 'Iran, Islamic Republic of']],
  ['IS', ['Iceland']],
  ['IT', ['Italy']],
  ['JE', ['Jersey']],
  ['JM', ['Jamaica']],
  ['JO', ['Jordan']],
  ['JP', ['Japan']],
  ['KE', ['Kenya']],
  ['KG', ['Kyrgyzstan']],
  ['KH', ['Cambodia']],
  ['KI', ['Kiribati']],
  ['KM', ['Comoros']],
  ['KN', ['Saint Kitts and Nevis']],
  ['KP', ['North Korea', "Korea, Democratic People's Republic of"]],
  ['KR', ['South Korea', 'Korea, Republic of', 'Republic of Korea']],
  ['KW', ['Kuwait']],
  ['KY', ['Cayman Islands']],
  ['KZ', ['Kazakhstan']],
  ['LA', ['Laos', "Lao People's Democratic Republic"]],
  ['LB', ['Lebanon']],
  ['LC', ['Saint Lucia']],
  ['LI', ['Liechtenstein']],
  ['LK', ['Sri Lanka']],
  ['LR', ['Liberia']],
  ['LS', ['Lesotho']],
  ['LT', ['Lithuania']],
  ['LU', ['Luxembourg']],
  ['LV', ['Latvia']],
  ['LY', ['Libya']],
  ['MA', ['Morocco']],
  ['MC', ['Monaco']],
  ['MD', ['Moldova', 'Moldova, Republic of']],
  ['ME', ['Montenegro']],
  ['MF', ['Saint Martin', 'Saint Martin (French part)']],
  ['MG', ['Madagascar']],
  ['MH', ['Marshall Islands']],
  ['MK', ['North Macedonia', 'Macedonia']],
  ['ML', ['Mali']],
  ['MM', ['Myanmar', 'Burma']],
  ['MN', ['Mongolia']],
  ['MO', ['Macao', 'Macau']],
  ['MP', ['Northern Mariana Islands']],
  ['MQ', ['Martinique']],
  ['MR', ['Mauritania']],
  ['MS', ['Montserrat']],
  ['MT', ['Malta']],
  ['MU', ['Mauritius']],
  ['MV', ['Maldives']],
  ['MW', ['Malawi']],
  ['MX', ['Mexico']],
  ['MY', ['Malaysia']],
  ['MZ', ['Mozambique']],
  ['NA', ['Namibia']],
  ['NC', ['New Caledonia']],
  ['NE', ['Niger']],
  ['NF', ['Norfolk Island']],
  ['NG', ['Nigeria']],
  ['NI', ['Nicaragua']],
  ['NL', ['Netherlands', 'The Netherlands']],
  ['NO', ['Norway']],
  ['NP', ['Nepal']],
  ['NR', ['Nauru']],
  ['NU', ['Niue']],
  ['NZ', ['New Zealand']],
  ['OM', ['Oman']],
  ['PA', ['Panama']],
  ['PE', ['Peru']],
  ['PF', ['French Polynesia']],
  ['PG', ['Papua New Guinea']],
  ['PH', ['Philippines']],
  ['PK', ['Pakistan']],
  ['PL', ['Poland']],
  ['PM', ['Saint Pierre and Miquelon']],
  ['PN', ['Pitcairn', 'Pitcairn Islands']],
  ['PR', ['Puerto Rico']],
  ['PS', ['Palestine', 'Palestine, State of', 'Palestinian Territory']],
  ['PT', ['Portugal']],
  ['PW', ['Palau']],
  ['PY', ['Paraguay']],
  ['QA', ['Qatar']],
  ['RE', ['Réunion', 'Reunion']],
  ['RO', ['Romania']],
  ['RS', ['Serbia']],
  ['RU', ['Russia', 'Russian Federation']],
  ['RW', ['Rwanda']],
  ['SA', ['Saudi Arabia']],
  ['SB', ['Solomon Islands']],
  ['SC', ['Seychelles']],
  ['SD', ['Sudan']],
  ['SE', ['Sweden']],
  ['SG', ['Singapore']],
  ['SH', ['Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha']],
  ['SI', ['Slovenia']],
  ['SJ', ['Svalbard and Jan Mayen']],
  ['SK', ['Slovakia']],
  ['SL', ['Sierra Leone']],
  ['SM', ['San Marino']],
  ['SN', ['Senegal']],
  ['SO', ['Somalia']],
  ['SR', ['Suriname']],
  ['SS', ['South Sudan']],
  ['ST', ['Sao Tome and Principe', 'São Tomé and Príncipe']],
  ['SV', ['El Salvador']],
  ['SX', ['Sint Maarten', 'Sint Maarten (Dutch part)']],
  ['SY', ['Syria', 'Syrian Arab Republic']],
  ['SZ', ['Eswatini', 'Swaziland']],
  ['TC', ['Turks and Caicos Islands']],
  ['TD', ['Chad']],
  ['TF', ['French Southern Territories']],
  ['TG', ['Togo']],
  ['TH', ['Thailand']],
  ['TJ', ['Tajikistan']],
  ['TK', ['Tokelau']],
  ['TL', ['Timor-Leste', 'East Timor']],
  ['TM', ['Turkmenistan']],
  ['TN', ['Tunisia']],
  ['TO', ['Tonga']],
  ['TR', ['Turkey', 'Türkiye', 'Turkiye']],
  ['TT', ['Trinidad and Tobago']],
  ['TV', ['Tuvalu']],
  ['TW', ['Taiwan', 'Taiwan, Province of China']],
  ['TZ', ['Tanzania', 'Tanzania, United Republic of']],
  ['UA', ['Ukraine']],
  ['UG', ['Uganda']],
  ['UM', ['United States Minor Outlying Islands']],
  ['US', ['United States', 'United States of America', 'USA']],
  ['UY', ['Uruguay']],
  ['UZ', ['Uzbekistan']],
  ['VA', ['Vatican City', 'Holy See (Vatican City State)']],
  ['VC', ['Saint Vincent and the Grenadines']],
  ['VE', ['Venezuela', 'Venezuela, Bolivarian Republic of']],
  ['VG', ['British Virgin Islands', 'Virgin Islands, British']],
  ['VI', ['U.S. Virgin Islands', 'Virgin Islands, U.S.']],
  ['VN', ['Vietnam', 'Viet Nam']],
  ['VU', ['Vanuatu']],
  ['WF', ['Wallis and Futuna']],
  ['WS', ['Samoa']],
  ['XK', ['Kosovo']],
  ['YE', ['Yemen']],
  ['YT', ['Mayotte']],
  ['ZA', ['South Africa']],
  ['ZM', ['Zambia']],
  ['ZW', ['Zimbabwe']],
];

const ALPHA2_SET = new Set<string>();
for (const [code, names] of CANONICAL) {
  ALPHA2_SET.add(code);
  for (const name of names) {
    NAME_TO_ALPHA2[name.toLowerCase()] = code;
  }
}

/**
 * Convert a country value to an ISO 3166-1 alpha-2 code suitable for the
 * ClickHouse FixedString(2) column.
 *
 * - Already a valid 2-letter code → returned uppercased.
 * - A known country name (or alias) → its alpha-2 code.
 * - Anything else → '' (safe to store, never overflows).
 */
export function toCountryCode(value?: string | null): string {
  if (!value) {
    return '';
  }
  const trimmed = value.trim();
  if (trimmed.length === 2 && ALPHA2_SET.has(trimmed.toUpperCase())) {
    return trimmed.toUpperCase();
  }
  return NAME_TO_ALPHA2[trimmed.toLowerCase()] ?? '';
}
