// biome-ignore format: annoying

const data = {
  amazon: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Amazon_icon.svg',
  'chromium os': 'https://upload.wikimedia.org/wikipedia/commons/2/28/Chromium_Logo.svg',
  'mac os': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/MacOS_logo.svg/1200px-MacOS_logo.svg.png',
  apple: 'https://sladesportfolio.wordpress.com/wp-content/uploads/2015/08/apple_logo_black-svg.png',
  huawei: 'https://upload.wikimedia.org/wikipedia/en/0/04/Huawei_Standard_logo.svg',
  xiaomi: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Xiaomi_logo.svg',
  sony: 'https://serialtrainer7.com/wp-content/uploads/2021/07/sony-logo-300px-square.png',
  lg: 'https://upload.wikimedia.org/wikipedia/commons/2/20/LG_symbol.svg',
  samsung: 'https://seekvectors.com/storage/images/Samsung-Logo-22.svg',
  oppo: 'https://indoleads.nyc3.cdn.digitaloceanspaces.com/uploads/offers/logos/8695_95411e367b832.png',
  motorola: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Motorola_M_symbol_blue.svg',
  oneplus: 'https://pbs.twimg.com/profile_images/1709165009148809216/ebHb4xhF_400x400.png',
  asus: 'https://cdn-icons-png.freepik.com/512/5969/5969050.png',
  fairphone: 'https://cdn.dribbble.com/users/433772/screenshots/2109827/fairphone_dribbble.jpg',
  nokia: 'https://www.gizchina.com/wp-content/uploads/images/2023/02/Nokia-logo.webp',
  'mobile safari': 'https://upload.wikimedia.org/wikipedia/commons/5/52/Safari_browser_logo.svg',
  'openpanel.dev': 'https://openpanel.dev',
  'samsung internet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Samsung_Internet_logo.svg/1024px-Samsung_Internet_logo.svg.png',
  'vstat.info': 'https://vstat.info',
  'yahoo!': 'https://yahoo.com',
  android: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Android_robot.svg/1745px-Android_robot.svg.png',
  'android browser': 'https://image.similarpng.com/very-thumbnail/2020/08/Android-icon-on-transparent--background-PNG.png',
  silk: 'https://m.media-amazon.com/images/I/51VCjQCvF0L.png',
  kakaotalk: 'https://www.kakaocorp.com/',
  bing: 'https://bing.com',
  electron: 'https://www.electronjs.org',
  whale: 'https://whale.naver.com',
  wechat: 'https://wechat.com',
  chrome: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Google_Chrome_icon_%28February_2022%29.svg',
  'chrome webview': 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Google_Chrome_icon_%28February_2022%29.svg',
  'chrome headless': 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Google_Chrome_icon_%28February_2022%29.svg',
  chromecast: 'https://upload.wikimedia.org/wikipedia/commons/archive/2/26/20161130022732%21Chromecast_cast_button_icon.svg',
  webkit: 'https://webkit.org',
  duckduckgo: 'https://duckduckgo.com',
  ecosia: 'https://ecosia.com',
  edge: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Microsoft_Edge_logo_%282019%29.png',
  facebook: 'https://facebook.com',
  firefox: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Firefox_logo%2C_2019.svg/1920px-Firefox_logo%2C_2019.svg.png',
  github: 'https://github.com',
  gmail: 'https://mail.google.com',
  google: 'https://google.com',
  gsa: 'https://google.com', // Google Search App
  instagram: 'https://instagram.com',
  ios: 'https://cdn0.iconfinder.com/data/icons/flat-round-system/512/apple-1024.png',
  linkedin: 'https://linkedin.com',
  linux: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg',
  ubuntu: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo-ubuntu_cof-orange-hex.svg',
  weibo: 'https://en.wikipedia.org/wiki/Weibo#/media/File:Sina_Weibo.svg',
  microlaunch: 'https://microlaunch.net',
  openalternative: 'https://openalternative.co',
  opera: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Opera_2015_icon.svg/1920px-Opera_2015_icon.svg.png',
  pinterest: 'https://www.pinterest.se',
  producthunt: 'https://www.producthunt.com',
  reddit: 'https://reddit.com',
  safari: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Safari_browser_logo.svg',
  slack: 'https://slack.com',
  snapchat: 'https://snapchat.com',
  taaft: 'https://theresanaiforthat.com',
  twitter: 'https://twitter.com',
  windows: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Windows_logo_-_2012.png',
  yandex: 'https://yandex.com',
  youtube: 'https://youtube.com',
  ossgallery: 'https://oss.gallery',
  convertkit: 'https://convertkit.com',
  whatsapp: 'https://www.whatsapp.com/',
  telegram: 'https://telegram.org/',
  tiktok: 'https://tiktok.com',
  sharpspring: 'https://sharpspring.com',
  'hacker news': 'https://news.ycombinator.com',
  betalist: 'https://betalist.com',
  qwant: 'https://www.qwant.com',
  flipboard: 'https://flipboard.com/',
  trustpilot: 'https://trustpilot.com',
  'outlook.com': 'https://login.live.com/',
};

export default data;
