// biome-ignore format: annoying

const data = {
  amazon: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Amazon_icon.svg',
  'chromium os': 'https://upload.wikimedia.org/wikipedia/commons/2/28/Chromium_Logo.svg',
  'mac os': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/MacOS_logo.svg/1200px-MacOS_logo.svg.png',
  apple: 'https://sladesportfolio.wordpress.com/wp-content/uploads/2015/08/apple_logo_black-svg.png',
  huawei: 'https://upload.wikimedia.org/wikipedia/en/0/04/Huawei_Standard_logo.svg',
  xiaomi: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Xiaomi_logo.svg',
  sony: 'https://serialtrainer7.com/wp-content/uploads/2021/07/sony-logo-300px-square.png',
  lg: 'https://upload.wikimedia.org/wikipedia/commons/2/20/LG_symbol.svg',
  samsung: 'https://seekvectors.com/storage/images/Samsung-Logo-22.svg',
  oppo: 'https://indoleads.nyc3.cdn.digitaloceanspaces.com/uploads/offers/logos/8695_95411e367b832.png',
  motorola: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Motorola_M_symbol_blue.svg',
  oneplus: 'https://pbs.twimg.com/profile_images/1709165009148809216/ebHb4xhF_400x400.png',
  asus: 'https://cdn-icons-png.freepik.com/512/5969/5969050.png',
  fairphone: 'https://cdn.dribbble.com/users/433772/screenshots/2109827/fairphone_dribbble.jpg',
  nokia: 'https://www.gizchina.com/wp-content/uploads/images/2023/02/Nokia-logo.webp',
  'mobile safari': 'https://upload.wikimedia.org/wikipedia/commons/5/52/Safari_browser_logo.svg',
  'openpanel.dev': 'https://openpanel.dev',
  'samsung internet': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Samsung_Internet_logo.svg/1024px-Samsung_Internet_logo.svg.png',
  'vstat.info': 'https://vstat.info',
  'yahoo!': 'https://yahoo.com',
  android: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Android_robot.svg/1745px-Android_robot.svg.png',
  'android browser': 'https://image.similarpng.com/very-thumbnail/2020/08/Android-icon-on-transparent--background-PNG.png',
  silk: 'https://m.media-amazon.com/images/I/51VCjQCvF0L.png',
  kakaotalk: 'https://www.kakaocorp.com/',
  bing: 'https://bing.com',
  electron: 'https://www.electronjs.org',
  whale: 'https://whale.naver.com',
  wechat: 'https://wechat.com',
  chrome: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Google_Chrome_icon_%28February_2022%29.svg',
  'mobile chrome': 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Google_Chrome_icon_%28February_2022%29.svg',
  'chrome webview': 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Google_Chrome_icon_%28February_2022%29.svg',
  'chrome headless': 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Google_Chrome_icon_%28February_2022%29.svg',
  chromecast: 'https://upload.wikimedia.org/wikipedia/commons/archive/2/26/20161130022732%21Chromecast_cast_button_icon.svg',
  webkit: 'https://webkit.org',
  duckduckgo: 'https://duckduckgo.com',
  ecosia: 'https://ecosia.com',
  edge: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Microsoft_Edge_logo_%282019%29.png',
  facebook: 'https://facebook.com',
  firefox: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Firefox_logo%2C_2019.svg/1920px-Firefox_logo%2C_2019.svg.png',
  'mobile firefox': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Firefox_logo%2C_2019.svg/1920px-Firefox_logo%2C_2019.svg.png',
  github: 'https://github.com',
  gmail: 'https://mail.google.com',
  google: 'https://google.com',
  gsa: 'https://google.com', // Google Search App
  instagram: 'https://instagram.com',
  ios: 'https://cdn0.iconfinder.com/data/icons/flat-round-system/512/apple-1024.png',
  linkedin: 'https://linkedin.com',
  linux: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Tux.svg',
  ubuntu: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo-ubuntu_cof-orange-hex.svg',
  weibo: 'https://en.wikipedia.org/wiki/Weibo#/media/File:Sina_Weibo.svg',
  microlaunch: 'https://microlaunch.net',
  openalternative: 'https://openalternative.co',
  opera: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Opera_2015_icon.svg/1920px-Opera_2015_icon.svg.png',
  'opera touch': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Opera_2015_icon.svg/1920px-Opera_2015_icon.svg.png',
  'miui browser': 'https://www.apkmirror.com/wp-content/themes/APKMirror/ap_resize/ap_resize.php?src=https%3A%2F%2Fdownloadr2.apkmirror.com%2Fwp-content%2Fuploads%2F2020%2F07%2F79%2F5f06abb0c532a.png',
  'huawei browser': 'https://www.apkmirror.com/wp-content/themes/APKMirror/ap_resize/ap_resize.php?src=https%3A%2F%2Fdownloadr2.apkmirror.com%2Fwp-content%2Fuploads%2F2021%2F09%2F49%2F613e45827fe31.png',
  'vivo browser': 'https://play-lh.googleusercontent.com/SYGXsBZOFsI4p72IoWtJiuAdp2Acv0WB4e6R1jxNcQdPcOdP1sXk_Cfcr1KBt2lzZQ=w480-h960-rw',
  'qqbrowser': 'https://cdn6.aptoide.com/imgs/6/1/4/614713aba4f9ca93a4e20257014d0713_icon.png',
  'quark': 'https://play-lh.googleusercontent.com/o__Uwu3TEsDVJ92m6zacy2GXotP2faFAlLQJOgOxYFsgoDkDYwODQ4STHY1fe0n_imlpiiUiE-QgRQaWdyi99w=w240-h480-rw',
  pinterest: 'https://www.pinterest.se',
  producthunt: 'https://www.producthunt.com',
  reddit: 'https://reddit.com',
  safari: 'https://upload.wikimedia.org/wikipedia/commons/5/52/Safari_browser_logo.svg',
  slack: 'https://slack.com',
  snapchat: 'https://snapchat.com',
  taaft: 'https://theresanaiforthat.com',
  twitter: 'https://twitter.com',
  windows: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Windows_logo_-_2012.png',
  yandex: 'https://yandex.com',
  youtube: 'https://youtube.com',
  ossgallery: 'https://oss.gallery',
  convertkit: 'https://convertkit.com',
  whatsapp: 'https://www.whatsapp.com/',
  telegram: 'https://telegram.org/',
  tiktok: 'https://tiktok.com',
  sharpspring: 'https://sharpspring.com',
  'hacker news': 'https://news.ycombinator.com',
  betalist: 'https://betalist.com',
  qwant: 'https://www.qwant.com',
  flipboard: 'https://flipboard.com/',
  trustpilot: 'https://trustpilot.com',
  'outlook.com': 'https://login.live.com/',
  notion: 'https://notion.so',
  brave: 'https://brave.com',
  perplexity: 'https://perplexity.ai',
  vercel: 'https://vercel.com',
  discord: 'https://discord.com',
  openstatus: 'https://openstatus.dev',
  baidu: 'https://baidu.com',
  medium: 'https://medium.com',
  "google news": "https://news.google.com",
  "google ads": "https://ads.google.com",
  "google shopping": "https://www.google.com/shopping",
  "gmb": "https://business.google.com",
  "google business profile": "https://business.google.com",
  "yahoo": "https://www.yahoo.com",
  "yahoo! mail": "https://mail.yahoo.com",
  "yahoo! images": "https://images.search.yahoo.com",
  "startpagina": "https://www.startpagina.nl",
  "ask": "https://www.ask.com",
  "lycos": "https://www.lycos.com",
  "infospace": "https://www.infospace.com",
  "shenma": "https://m.sm.cn",
  "360.cn": "https://www.360.cn",
  "naver": "https://www.naver.com",
  "daum": "https://www.daum.net",
  "seznam": "https://www.seznam.cz",
  "seznam mail": "https://email.seznam.cz",
  "t-online": "https://www.t-online.de",
  "web.de": "https://web.de",
  "gmx": "https://www.gmx.net",
  "mail.ru": "https://mail.ru",
  "mail.com": "https://www.mail.com",
  "orange webmail": "https://mail.orange.fr",
  "aol": "https://www.aol.com",
  "aol mail": "https://mail.aol.com",
  "fb": "https://www.facebook.com",
  "facebook ads": "https://www.facebook.com/business/ads",
  "meta": "https://about.facebook.com",
  "meta_ads": "https://www.facebook.com/business/ads",
  "ig": "https://www.instagram.com",
  "threads": "https://www.threads.net",
  "x": "https://x.com",
  "pinterst": "https://www.pinterest.com",
  "twitch": "https://www.twitch.tv",
  "quora": "https://www.quora.com",
  "bluesky": "https://bsky.app",
  "vkontakte": "https://vk.com",
  "substack": "https://substack.com",
  "taboola": "https://www.taboola.com",
  "outbrain": "https://www.outbrain.com",
  "criteo": "https://www.criteo.com",
  "doubleclick": "https://doubleclick.net",
  "rakuten": "https://www.rakuten.com",
  "paypal": "https://www.paypal.com",
  "ebay": "https://www.ebay.com",
  "gitlab": "https://gitlab.com",
  "stack overflow": "https://stackoverflow.com",
  "figma": "https://www.figma.com",
  "dropbox": "https://www.dropbox.com",
  "openai": "https://openai.com",
  "chatgpt.com": "https://chatgpt.com",
  "mailchimp": "https://mailchimp.com",
  "activecampaign": "https://www.activecampaign.com",
  "customer.io": "https://customer.io",
  "iterable": "https://iterable.com",
  "moengage": "https://www.moengage.com",
  "klaviyo": "https://www.klaviyo.com",
  "brevo": "https://www.brevo.com",
  "tumblr": "https://www.tumblr.com",
  "dailymotion": "https://www.dailymotion.com",
};

export default data;
