import fs from 'node:fs';
import path from 'node:path';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
import yaml from 'js-yaml';

// Regex special characters that indicate we need actual regex
const regexSpecialChars = /[|^$.*+?(){}\[\]\\]/;

// User agents that must NEVER be treated as bots, even though the upstream
// device-detector list flags them. Its "Generic Bot" pattern lumps bare
// runtime/client identifiers (e.g. `node`, `Node.js`) into an anchored
// alternation because browsers never send them — but legitimate server-side
// traffic does. We only want to flag traffic whose user agent *explicitly*
// identifies itself as a bot (handled by the separate `bot|crawler|spider...`
// heuristic), so these plain identifiers are stripped out of the generated
// patterns here. This runs on every regen, so upstream can never re-introduce
// the false positives. Values are matched against single alternation branches,
// so regex metacharacters must be escaped exactly as they appear upstream.
export const ALLOWLISTED_BOT_UA_TOKENS = new Set(['node', 'Node\\.js']);

// Removes allowlisted identifiers from anchored exact-match groups such as
// `^(?:chrome|node|Node\.js|url)$`, leaving the genuinely suspicious branches
// intact. If a group ends up empty it is dropped together with a trailing `|`
// so the surrounding alternation stays valid.
export function stripAllowlistedTokens(regex: string): string {
  return regex.replace(
    /\^\(\?:([^)]+)\)\$\|?/g,
    (match: string, inner: string) => {
      const kept = inner
        .split('|')
        .filter((alt) => !ALLOWLISTED_BOT_UA_TOKENS.has(alt));

      if (kept.length === 0) {
        return '';
      }

      const trailingPipe = match.endsWith('|') ? '|' : '';
      return `^(?:${kept.join('|')})$${trailingPipe}`;
    },
  );
}

function transformBots(bots: any[]): any[] {
  return bots.map((bot) => {
    const { regex: rawRegex, ...rest } = bot;
    const regex = stripAllowlistedTokens(rawRegex);
    const hasRegexChars = regexSpecialChars.test(regex);

    if (hasRegexChars) {
      // Keep as regex
      return { regex, ...rest };
    }
    // Convert to includes
    return { includes: regex, ...rest };
  });
}

async function main() {
  // Get document, or throw exception on error
  try {
    const data = await fetch(
      'https://raw.githubusercontent.com/matomo-org/device-detector/master/regexes/bots.yml',
    ).then((res) => res.text());

    const parsedData = yaml.load(data) as any[];
    const transformedBots = transformBots(parsedData);

    fs.writeFileSync(
      path.resolve(__dirname, '../src/bots/bots.ts'),
      [
        '// This file is generated by the script get-bots.ts',
        '',
        '// The data is fetch from device-detector https://raw.githubusercontent.com/matomo-org/device-detector/master/regexes/bots.yml',
        '',
        `const bots = ${JSON.stringify(transformedBots, null, 2)} as const;`,
        'export default bots;',
        '',
      ].join('\n'),
      'utf-8',
    );

    console.log(
      `✅ Generated bots.ts with ${transformedBots.length} bot entries`,
    );
    const regexCount = transformedBots.filter((b) => 'regex' in b).length;
    const includesCount = transformedBots.filter((b) => 'includes' in b).length;
    console.log(`   - ${includesCount} simple string matches (includes)`);
    console.log(`   - ${regexCount} regex patterns`);
  } catch (e) {
    console.log(e);
  }
}

// Only fetch + regenerate when run directly (e.g. `pnpm gen:bots`), so the
// transformation helpers can be imported and unit-tested without a network call.
if (process.argv[1] === __filename) {
  main();
}
