import Head from "next/head";

import { useEffect, useState } from "react";
import { ReportSidebar } from "@/components/report/sidebar/ReportSidebar";
import { ReportLineChart } from "@/components/report/chart/ReportLineChart";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Combobox } from "@/components/ui/combobox";
import { useDispatch, useSelector } from "@/redux";
import { changeInterval } from "@/components/report/reportSlice";
import { type IInterval } from "@/types";

export default function Home() {
  const dispatch = useDispatch();
  const interval = useSelector((state) => state.report.interval);
  const events = useSelector((state) => state.report.events);
  const breakdowns = useSelector((state) => state.report.breakdowns);
  const startDate = useSelector((state) => state.report.startDate);
  const endDate = useSelector((state) => state.report.endDate);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen grid-cols-[400px_minmax(0,1fr)] divide-x">
        <div>
          <ReportSidebar />
        </div>

        <div className="flex flex-col gap-4 p-4">
          <div className="flex gap-4">
            <RadioGroup>
              <RadioGroupItem>7 days</RadioGroupItem>
              <RadioGroupItem>14 days</RadioGroupItem>
              <RadioGroupItem>1 month</RadioGroupItem>
              <RadioGroupItem>3 month</RadioGroupItem>
              <RadioGroupItem>6 month</RadioGroupItem>
              <RadioGroupItem>1 year</RadioGroupItem>
            </RadioGroup>
            <div className="w-full max-w-[200px]">
              <Combobox
                placeholder="Interval"
                onChange={(value) => {
                  dispatch(changeInterval(value as IInterval));
                }}
                value={interval}
                items={[
                  {
                    label: "Hour",
                    value: "hour",
                  },
                  {
                    label: "Day",
                    value: "day",
                  },
                  {
                    label: "Month",
                    value: "month",
                  },
                ]}
              ></Combobox>
            </div>
          </div>
          {startDate && endDate && (
            <ReportLineChart
              startDate={startDate}
              endDate={endDate}
              events={events}
              breakdowns={breakdowns}
              interval={interval}
            />
          )}
        </div>
      </main>
    </>
  );
}
